# Generated by Django 5.2 on 2025-04-22 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username_validator_wallet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="basic1_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="basic2_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="funding_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pre_starter_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_bonus_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Referral code must be 10 characters long and contain only uppercase letters and numbers.",
                        regex="^[A-Z0-9]{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="standard_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="starter_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ultimate1_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ultimate2_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Wallet balance cannot be negative"
                    )
                ],
            ),
        ),
    ]
