# Generated by Django 5.2 on 2025-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=50,
            ),
        ),
    ]
