# Generated by Django 5.2 on 2023-06-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_update_plan_add_queue_wallet_referral'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        # Update Withdrawal model
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_type',
            field=models.CharField(
                choices=[
                    ('SUBSCRIPTION', 'Subscription Withdrawal'),
                    ('WALLET', 'Wallet Withdrawal'),
                    ('REFERRAL', 'Referral Bonus Withdrawal')
                ],
                default='WALLET',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='subscription',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='withdrawals',
                to='subscriptions.subscription'
            ),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='withdrawals',
                to='subscriptions.wallet'
            ),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='withdrawals',
                to='users.user'
            ),
        ),
    ]