# Generated by Django 5.2 on 2025-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_update_withdrawal_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="bank_details",
            field=models.TextField(
                blank=True, help_text="Bank account details for bank transfers", null=True
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                help_text="Cryptocurrency wallet address for crypto withdrawals",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="withdrawal_type",
            field=models.CharField(
                choices=[("BANK", "Bank Transfer"), ("CRYPTO", "Cryptocurrency")],
                default="BANK",
                max_length=20,
            ),
        ),
    ]
