# Generated by Django 5.2 on 2025-04-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_update_plan_add_queue_wallet_referral"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queueposition",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="next_plan",
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["queue_position"]},
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="created_at",
            new_name="joined_at",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subscription",
            name="available_for_withdrawal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="total_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="queue_position",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions_made",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "to_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions_received",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("PRE_STARTER", "Pre-Starter Plan"),
                            ("STARTER", "Starter Plan"),
                            ("BASIC_1", "Basic 1"),
                            ("BASIC_2", "Basic 2"),
                            ("STANDARD", "Standard"),
                            ("ULTIMATE_1", "Ultimate 1"),
                            ("ULTIMATE_2", "Ultimate 2"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contribution_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount user contributes to join this plan",
                        max_digits=10,
                    ),
                ),
                (
                    "total_received",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount received from members",
                        max_digits=10,
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        help_text="Number of members needed to complete the queue (8 or 13)"
                    ),
                ),
                (
                    "deduction_repurchase",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount deducted for repurchase (1/13 of contribution)",
                        max_digits=10,
                    ),
                ),
                (
                    "deduction_maintenance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount deducted for maintenance (2/13 of contribution)",
                        max_digits=10,
                    ),
                ),
                (
                    "withdrawable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount available for withdrawal after deductions",
                        max_digits=10,
                    ),
                ),
                (
                    "next_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next plan to upgrade to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_plans",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["contribution_amount"],
            },
        ),
        migrations.AlterField(
            model_name="queue",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to="subscriptions.plan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subscriptions.plan"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Only applicable for PLAN wallet type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.plan",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="QueuePosition",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
    ]
